my.corpus <- Corpus(DirSource("E://Semester 2//Business Intelligence and Big Data Analytics//input files//prac2b"))
my.corpus <- tm_map(my.corpus,removeWords,stopwords("english"))
my.tdm <- TermDocumentMatrix(my.corpus)
inspect(my.tdm)
my.df <- as.data.frame(inspect(my.tdm))
barplot(as.matrix(my.tdm))
barplot(as.matrix(my.tdm),col = c("red", "yellow", "green", "blue"))